[package]
name = "home_automation_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
crossterm = "0.27.0"
home_automation_common.workspace = true
ratatui = "0.26.2"
tracing.workspace = true
tui-textarea = "0.4.0"
