[package]
name = "home_automation_entity"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
home_automation_common.workspace = true
prost.workspace = true
rand = "0.8.5"
tracing.workspace = true
